### ISSUE TITLE
Update GitHub actions cache to use new approach for monorepos

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris#256]
https://github.com/actions/setup-node#caching-packages-dependencies

```
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '14'
    cache: 'npm'
    cache-dependency-path: subdir/package-lock.json
- run: npm install
- run: npm test
```
