### ISSUE TITLE
2.0.0-beta.16 ResourceList.Item CSS not compiled correctly

### ISSUE THREAD

**Issue by sdn90** [Shopify/polaris#299]
Line 3772 in compiled styles.css

```css
.Polaris-ResourceList-Item__Item--selectable{
  width:calc(1 + resource-list-item(translate-offset));
  ...
}
```

I've tried building the V2 branch and got the same result.

## Specifications

- Polaris version: 2.0.0-beta.16
- React version: 16.2.0
